sudo: required

services:
- docker

language: generic

env:
  global:
  - secure: lCCs7RO9i1oDLwxLe4mIavo7afuzEEsL+MZa9yVSu0NzG8n9SQ1ayo0/08tQJA+QBFjk5bJ/+F/79FlVXXT20SGoaF0oOTRm+605zyf522WCdQafMkzc7AD6L+Q7GuVt1Ik21KjSQfz7a/3VpuF7/bRQbQTiZ2JszfUNKi80N6JMLA69a4H3NslJ8M1W7EuOswAT/QZxLzSe3adPGdqlin5RCcjD0msWBZFmuNgYH3P7w8hCYbO2IAW+wMEO96PfqNmSLPK+pcEw1GL7/qrb4R9REqjLpZ/bVno2hweQDHYHlsZzYXukvPHu72Je5KS+QfKDrUdkZcEZDkp95+2XqbN1nlH6eabga0tIV9xHToUpjRRgWJ+DPc3I9lKAWxehKLg6Sgpaeqrr2MhXYholce/u4La6qmHKR0i7Bh5NmL61aDd4Auq7KD9Xp67gCvm7x7tdPFNxwUVjlYNCFkJRaf+DvVP6et5UVwiUqb006M+NcOgaxGpRbCO9nEZvxI2GPd5r6DrxG6eZ82SR8fOSgV2W0CuCVA9KOuSktnH6dt/bTbwoMCfo5lHX6mr500emKRXxLGnXogCYip7gpPZ+Ieg4wURaypeRK3f6KRMWwlFSX3oQ/P3MOpe2/heoNXIkxt8ShvCLHEATY6hjJuFIPvUgE0rT47gFy27NeE8lyiM=
  - secure: 4sY6HItV5zB5c3dTnF1dHHBd2vH4ac7EUS2+i8c/+yxMbYMLdHumcMOqVl+b2TiHOjU4KvU2JlIFpvL1hynynUyIWek9tT8YGH+ZExh6wqOKdExvUgHt4aqnwxq5mSWBUDKQaZkmTRUfdjDtsi273DBFgnHpoj47e9Dmjhh2WQNXxMfCSGhICbJkYbXe4AVXrFCVUhIWuVkqsr/aqenS6gc3pgfHEN9X8P3ylUEOIvlekdjwyOfmRs/Z659sVGp+STZoS/zZPqgm0FZ6ncQFRvvNCLUky29LFRBlMKAzBYU0S2YbLvNlbaGe34AOkAeowfzNZVS+BiqhsAW3/biPnhU+xf5Kp8X93o2+lv9X1HyYvNNFfIWxS6tNsj9BFGNbqQCMCNwX5VtGooP9xavey6Ap1E8y6iAyyIEl6ly5agwTL568SrtZMCfNZ9PIV+Slqn2z2fmymQj0F031X7AqhW9LkDEAtnOXEcK4Rk0cGLUX45c//E+TJplqy5Pn0Sq+HHkbmHbARsTKya119ONdLWZuTQ09dxghn+gjv3+kt6mhrZl5VDhtg5CqzS9kviiuYG1O9OZat12U0zFyuXt3ZE65i1rg3ujNF8ONsCmgFk4vVydudxWHj6S3GRUYI4BdNcnuHI8cF3lph+hG90okQvGYhg3xaGizL8MG0NbL5oA=

branches:
  only:
  - master
  - /^[0-9]+\.[0-9]+\.[0-9]+$/

fail_fast: true

script:
- export IMG=simbo/node
- export TAGGED=`if [[ "$TRAVIS_BRANCH" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then echo true; else echo false; fi`
- export TAG=`if $TAGGED; then echo $TRAVIS_BRANCH; else echo "latest"; fi`
- echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
- docker build -f Dockerfile -t $IMG:$TAG .
- docker build -f Dockerfile-slim -t $IMG:$TAG-slim .
- docker build -f Dockerfile-alpine -t $IMG:$TAG-alpine .
- if $TAGGED; then
    export TAG_MAJOR=`echo "$TAG" | sed -E 's/^([0-9]+).+$/\1/'`;
    export TAG_MINOR=`echo "$TAG" | sed -E 's/^([0-9]+\.[0-9]+).+$/\1/'`;
    docker tag $IMG:$TAG $IMG:$TAG_MAJOR;
    docker tag $IMG:$TAG $IMG:$TAG_MINOR;
    docker tag $IMG:$TAG-slim $IMG:$TAG_MAJOR-slim;
    docker tag $IMG:$TAG-slim $IMG:$TAG_MINOR-slim;
    docker tag $IMG:$TAG-alpine $IMG:$TAG_MAJOR-alpine;
    docker tag $IMG:$TAG-alpine $IMG:$TAG_MINOR-alpine;
  fi
- docker push $IMG:$TAG-slim
- docker build -f Dockerfile-gyp -t $IMG:$TAG-gyp .
- if $TAGGED; then
    docker tag $IMG:$TAG-gyp $IMG:$TAG_MAJOR-gyp;
    docker tag $IMG:$TAG-gyp $IMG:$TAG_MINOR-gyp;
  fi
- docker push $IMG
