FROM node:12.20.0-buster-slim

COPY assets/.profile /root/.profile

RUN set -ex; \
  sed -r -i -e 's/^(dockerImageName="simbo\/node)([-a-z"]+)$/\1-slim"/' /root/.profile; \
  ln -fs /usr/share/zoneinfo/Europe/Berlin /etc/localtime; \
  echo "export EDITOR='nano'" >> /root/.profile; \
  echo "export VISUAL='nano'" >> /root/.profile; \
  dpkg-reconfigure -f noninteractive tzdata; \
  yarn config set disable-self-update-check true; \
  apt-get update; \
  apt-get install -qq -y --no-install-recommends nano; \
  apt-get autoremove -qq -y; \
  apt-get autoclean -qq -y; \
  apt-get clean -qq -y; \
  rm -rf /var/lib/apt/lists/*
