FROM node:14.15.4-buster-slim

COPY assets/.profile /root/.profile

VOLUME /yarn-cache

RUN set -ex; \
  sed -r -i -e 's/^(dockerImageName="simbo\/node)([-a-z"]+)$/\1-gyp"/' /root/.profile; \
  ln -fs /usr/share/zoneinfo/Europe/Berlin /etc/localtime; \
  mv /root/.profile /root/.bashrc; \
  dpkg-reconfigure -f noninteractive tzdata; \
  yarn config set disable-self-update-check true; \
  yarn config set cache-folder /yarn-cache; \
  apt-get update -qq; \
  apt-get install -qq --no-install-recommends nano build-essential python >/dev/null; \
  apt-get autoremove -qq; \
  apt-get autoclean -qq; \
  apt-get clean -qq; \
  rm -rf /var/lib/apt/lists/*
