ARG VERSION=8.11.2

FROM simbo/node:${VERSION}-slim

RUN set -ex; \
  apt-get update; \
  apt-get install -qq --no-install-recommends \
    build-essential \
    python \
  ; \
  rm -rf /var/lib/apt/lists/*
