#!/bin/bash

# exit on errors
set -e

# semver version to release
version=$1

# formatting vars
term=${TERM:-"dumb"}
red=$(tput -T$term setaf 9)
green=$(tput -T$term setaf 10)
yellow=$(tput -T$term setaf 11)
blue=$(tput -T$term setaf 12)
white=$(tput -T$term setaf 15)
gray=$(tput -T$term setaf 8)
bold=$(tput -T$term bold)
normal=$(tput -T$term sgr0)

# test cli param and print usage information
if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  printf "Upgrade dockerfiles to given node.js version and release new images.\n\n"
  printf "Usage: ${white}${bold}$(basename "$0") <SEMVER_VERSION>${normal}\n\n"
  printf "Example: ${white}${bold}$(basename "$0") 8.11.2${normal}\n"
  exit 1
fi

# change to script directory
cd "$(dirname "$0")"

# test if git is available
command -v git >/dev/null 2>&1 || { printf >&2 "${red}git is required but not available.${normal}\n${gray}Aborting.${normal}\n"; exit 1; }

# test if current branch is master
currentBranch="$(git rev-parse --abbrev-ref HEAD)"
if [[ "$currentBranch" != "master" ]]; then
  printf "${red}Your current git branch should be master but is $currentBranch.${normal}\n${gray}Aborting.${normal}\n"
  exit 1
fi

# test if working tree is clean
if repoStatus=$(git status --untracked-files=no --porcelain) && [ ! -z "$repoStatus" ]; then
  printf "${red}Your git repository seems to have uncommitted changes.${normal}\n${gray}Aborting.${normal}\n"
  exit 1
fi

# extract major and minor parts from version for confirmation message
versionMajor=`echo "$version" | sed -E 's/^([0-9]+).+$/\1/'`
versionMinor=`echo "$version" | sed -E 's/^([0-9]+\.[0-9]+).+$/\1/'`

# confirm actions
printf "\n📦 ${white}${bold}Publish new Versions for ${yellow}simbo/docker-node${normal}\n"
printf "\nThis script will update all dockerfiles in this repository to \n"
printf "\n    ${yellow}${bold}node.js v${version}${normal}\n"
printf "\nChanges will be committed, tagged with ${white}${bold}${version}${normal} and pushed to GitHub.\n"
printf "This push should trigger GitHub Actions, where images will be built and released to Docker Hub, where they will be tagged with "
printf "${white}${bold}${versionMajor}${normal}, ${white}${bold}${versionMinor}${normal} and ${white}${bold}${version}${normal}.\n"
printf "\nPress ${white}${bold}[ENTER] to continue${normal} or anything else to cancel."
IFS= read -s -n 1 key
echo ""
if [[ $key != "" ]]; then
  printf "${gray}Cancelled.${normal}\n"
  exit 1
fi
echo ""

# message for committing and tagging
message="node.js v$version"

# files list
declare -a files=(
  "Dockerfile"
  "Dockerfile-slim"
  "Dockerfile-gyp"
  "Dockerfile-alpine"
)

# change files and add changes to git
for file in "${files[@]}"; do
  sed -i '' -E 's/^(FROM[[:space:]]+)(node:)([0-9]+\.[0-9]+\.[0-9]+)/\1\2'$version'/' $file
  git add $file
done

# commit changes
git commit -m "$message"

# remove tag if existing locally and remote, then add new tag
set +e
git tag -d $version >/dev/null 2>&1
git push origin :refs/tags/$version >/dev/null 2>&1
git push --delete origin $version >/dev/null 2>&1
set -e
git tag -a $version -m "$message"

# push changes and tags
git push --tags origin master

# print success message
printf "\n✅ ${green}All done.${normal}\n"
printf "\nSee GitHub Actions for CI details: ${blue}https://github.com/simbo/docker-node/actions${normal}\n"
printf "See Docker Hub for released images: ${blue}https://hub.docker.com/r/simbo/node/tags${normal}\n"
exit 0
